[package]
name = "markdown-extract-cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "markdown-extract"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.89"
clap = { version = "4.5.20", features = ["derive"] }
markdown-extract = { path = "../markdown-extract" }
regex = "1.3"
