name: 'Extract Markdown Section'
description: 'Extract sections of a markdown file with a regular expression! Great for changelogs ;)'
inputs:
  file:
    description: 'The input file'
    required: true
  pattern:
    description: 'Pattern to match against headings'
    required: true
runs:
  using: 'docker'
  image: 'docker://sean0x42/markdown-extract:v2'
