name: 'Extract Markdown Section'
description: 'Extract sections of a markdown file with a regular expression! Great for changelogs ;)'
inputs:
  file:
    description: 'The input file'
    required: true
  pattern:
    description: 'Pattern to match against headings'
    required: true
outputs:
  markdown:
    description: The extracted Markdown section body.
runs:
  using: 'docker'
  image: 'Dockerfile-action'
  args:
    - ${{ inputs.pattern }}
    - ${{ inputs.file }}
