[package]
name = "markdown-magic"
description = "Magic tools for markdown."
version = "2.0.0-beta"
authors = ["Sean Bailey <hello@seanbailey.dev>"]
license = "MIT"
repository = "https://github.com/sean0x42/markdown-extract"
keywords = ["markdown", "magic"]
edition = "2018"
exclude = [".github/*"]
readme = "README.md"

[[bin]]
name = "markdown-magic"
path = "src/bin.rs"

[dependencies]
log = "0.4"
regex = "1.3"
structopt = "0.3"
