name: Test the Github Action
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          file: CHANGELOG.md
          pattern: "v2.0.0"
      - uses: ./
        with:
          file: CHANGELOG.md
          pattern: "this does not exist"
