name: Build & Test
on: [push]
jobs:
  build-rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Verify package builds
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose

  build-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Verify docker image builds
        run: docker build .
